language: node_js
node_js: "node"
os: osx
env:
  - HOMEBREW_NO_AUTO_UPDATE=1
before_install:
  - brew install bash
  - brew install rust
script:
  - npm run generate
  - npm run cpp
  - npm run go
  - npm run py
  - npm run rs
  - npm run js

