language: node_js
node_js: "node"
os: osx
env:
  - HOMEBREW_NO_AUTO_UPDATE=1
before_install:
  - brew install bash
  - brew install rust
script:
  - npm run generate
  - npm run difftest
before_cache:
  - brew install gnu-sed --with-default-names
cache:
  directories:
    - node_modules
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Cellar/gnu-sed
    - /usr/local/bin
