language: node_js
node_js: "node"
os: osx
env:
  - HOMEBREW_NO_AUTO_UPDATE=1
before_install:
  - brew install bash
  - brew install gnu-sed --with-default-names
  - brew install rust
  - npm i
script:
  - npm run generate
  - npm run difftest
cache:
  directories:
    - node_modules
    - $HOME/Library/Caches/Homebrew
